name: CI

on:
  pull_request:
  push:
    branches:
      - main
  merge_group:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  pr-title:
    name: Pull request title
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-26.04
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ github.token }}

  result:
    name: CI result
    if: always()
    needs:
      - pr-title
    runs-on: ubuntu-26.04
    steps:
      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
